import 'package:flutter/material.dart';
import 'colors.dart';

final lightTheme = ThemeData(
  useMaterial3: true,
  brightness: Brightness.light,
  colorScheme: const ColorScheme(
    brightness: Brightness.light,
    primary: primaryLight,
    onPrimary: onPrimaryLight,
    primaryContainer: primaryContainerLight,
    onPrimaryContainer: onPrimaryContainerLight,
    secondary: secondaryLight,
    onSecondary: onSecondaryLight,
    secondaryContainer: secondaryContainerLight,
    onSecondaryContainer: onSecondaryContainerLight,
    tertiary: tertiaryLight,
    onTertiary: onTertiaryLight,
    tertiaryContainer: tertiaryContainerLight,
    onTertiaryContainer: onTertiaryContainerLight,
    error: errorLight,
    onError: onErrorLight,
    errorContainer: errorContainerLight,
    onErrorContainer: onErrorContainerLight,
    surface: surfaceLight,
    onSurface: onSurfaceLight,
    surfaceContainerHighest: surfaceContainerHighestLight,
    outline: outlineLight,
    outlineVariant: outlineVariantLight,
    shadow: scrimLight,
    scrim: scrimLight,
    inverseSurface: inverseSurfaceLight,
    onInverseSurface: inverseOnSurfaceLight,
    inversePrimary: inversePrimaryLight,
  ),
  textTheme: _buildTextTheme(Brightness.light),
);

final darkTheme = ThemeData(
  useMaterial3: true,
  brightness: Brightness.dark,
  colorScheme: const ColorScheme(
    brightness: Brightness.dark,
    primary: primaryDark,
    onPrimary: onPrimaryDark,
    primaryContainer: primaryContainerDark,
    onPrimaryContainer: onPrimaryContainerDark,
    secondary: secondaryDark,
    onSecondary: onSecondaryDark,
    secondaryContainer: secondaryContainerDark,
    onSecondaryContainer: onSecondaryContainerDark,
    tertiary: tertiaryDark,
    onTertiary: onTertiaryDark,
    tertiaryContainer: tertiaryContainerDark,
    onTertiaryContainer: onTertiaryContainerDark,
    error: errorDark,
    onError: onErrorDark,
    errorContainer: errorContainerDark,
    onErrorContainer: onErrorContainerDark,
    surface: surfaceDark,
    onSurface: onSurfaceDark,
    surfaceContainerHighest: surfaceContainerHighestDark,
    outline: outlineDark,
    outlineVariant: outlineVariantDark,
    shadow: scrimDark,
    scrim: scrimDark,
    inverseSurface: inverseSurfaceDark,
    onInverseSurface: inverseOnSurfaceDark,
    inversePrimary: inversePrimaryDark,
  ),
  textTheme: _buildTextTheme(Brightness.dark),
);

TextTheme _buildTextTheme(Brightness brightness) {
  return const TextTheme(
    displayLarge: TextStyle(fontFamily: 'Nunito'),
    displayMedium: TextStyle(fontFamily: 'Nunito'),
    displaySmall: TextStyle(fontFamily: 'Nunito'),
    headlineLarge: TextStyle(fontFamily: 'Nunito'),
    headlineMedium: TextStyle(fontFamily: 'Nunito'),
    headlineSmall: TextStyle(fontFamily: 'Nunito'),
    titleLarge: TextStyle(fontFamily: 'Nunito'),
    titleMedium: TextStyle(fontFamily: 'Nunito'),
    titleSmall: TextStyle(fontFamily: 'Nunito'),
    bodyLarge: TextStyle(fontFamily: 'Nunito'),
    bodyMedium: TextStyle(fontFamily: 'Nunito'),
    bodySmall: TextStyle(fontFamily: 'Nunito'),
    labelLarge: TextStyle(fontFamily: 'Nunito'),
    labelMedium: TextStyle(fontFamily: 'Nunito'),
    labelSmall: TextStyle(fontFamily: 'Nunito'),
  );
}
